config/routes.rb
Rails.application.routes.draw do
  resources :gossip
  resources :user
  resources :city
  resources :sessions, only: [:new, :create, :destroy]
  post 'user/new'
  delete '/logout', to: 'sessions#destroy', as: 'logout'
  #get 'static_pages/contact'
  #get 'static_pages/team'
  get 'contact', to: 'static_pages#contact'
  get 'team', to: 'static_pages#team'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/city.rb
class City < ApplicationRecord
    has_many :users
end

app/models/gossip.rb
class Gossip < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: { in: 3..14 }

    validates :content, presence: true
    
    
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :recipient_lists
end

app/models/recipient_list.rb
class RecipientList < ApplicationRecord
  belongs_to :private_message
  belongs_to :recipient, class_name: "User" 
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :gossips
  belongs_to :city
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :received_messages, foreign_key: 'recipient_id', class_name: "RecipientList"
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :age, presence: true
  validates :description, presence: true
  validates :city, presence: true
  validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  end

app/controllers/city_controller.rb
class CityController < ApplicationController

  def index
    @city = City.all
  end

  def show
    @city = City.find(params[:id])
  end
end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  before_action :require_login, only: [:new, :create]
  before_action :authorize_user, only: [:edit, :update, :destroy]

  def index
      @gossip = Gossip.all
  end
  
  def show
      @gossip = Gossip.find(params[:id])
  end


  def new
      @gossip = Gossip.new
  end
  
  def create
      @gossip = current_user.gossips.build(title: params[:title], content: params[:content])
      if @gossip.save
        flash[:success] = "Potin bien créé !"
        redirect_to root_path
      else
        render 'new'
      end
    end 

  def edit
      @gossip = Gossip.find(params[:id])
  end
  
  def update
      @gossip = Gossip.find(params[:id])
      post_params = params.require(:gossip).permit(:title, :content)
      @gossip.update(post_params)
      redirect_to gossip_path
  end

  def destroy
      @gossip = Gossip.find(params[:id])
      @gossip.destroy
      redirect_to root_path
  end

  private

  def require_login
    unless current_user
        flash[:error] = "Vous devez être connecté"
        redirect_to new_session_path
    end
end

private

def authorize_user
  @gossip = Gossip.find(params[:id])
  unless @gossip.user == current_user
    flash[:error] = "Vous n'êtes pas autorisé à modifier ou supprimer ce potin."
    redirect_to root_path
  end
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      redirect_to new_session_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
    @gossip = Gossip.all
    @user = User.all
  end

  def contact

  end

  def team

  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    # Méthode qui crée un user à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
    
    @user = User.new('first_name' => params[:first_name], 'last_name' => params[:last_name], 'email' => params[:email], 'password' => params[:password], 'city_id' => rand(City.all.first.id..City.all.last.id), 'description' => params[:description], 'age' => params[:age])
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  # retourne true si l'user est loggé
  def logged_in?
    session[:user_id] != nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/city/index.html.erb
<h1>City#index</h1>
<p>Find me in app/views/city/index.html.erb</p>

app/views/city/show.html.erb
<h1>City#show</h1>
<p>Find me in app/views/city/show.html.erb</p>

app/views/gossip/edit.html.erb
<h1>Editer un Gossip</h1>

<%= form_for @gossip do |f|%>
<div class="form-group">
<label>Titre du Gossip</label>
<%= f.text_field :title, class: 'form_control' %>
</div>

<div class="form-group">
<label>Contenu du Gossip</label>
<%= f.text_area :content, class: 'form-control' %>
</div>

<div class="form-group">
<button type="submit">Modifier le Gossip</button>
</div>

<% end %>


<%= button_to 'Supprimer', @gossip, method: :delete, data: { confirm: 'Êtes-vous sûr de vouloir supprimer ce gossip ?' }, class: 'btn btn-danger' %>

app/views/gossip/index.html.erb
<h2> Voici les gossips:</h2>

<% @gossip.each do |gossip| %>
<p><%= gossip.title %></p>
<p><%= gossip.content %></p>
<% end %>

app/views/gossip/new.html.erb
<%= form_tag url_for(action: 'create'), method: "post" do %>
        <div class="form-group">
          <%= label_tag 'Titre :' %>
          <%= text_field_tag 'title', @gossip.title, {class: 'form-control'} %>
        </div>
        <div class="form-group">
          <%= label_tag 'Contenu :' %>
          <%= text_area_tag 'content', @gossip.content, {class: 'form-control'} %>
        </div>
      
        <div class="row justify-content-center">
          <%= submit_tag "Créer le potin", {class: 'btn btn-primary'} %>
        </div>
      <% end %>

app/views/gossip/show.html.erb
<h2> Voici le gossip n<%= @gossip.id %> </h2>
<p><%= @gossip.user.first_name%> </p>
<p><%= @gossip.user.last_name%></p>
<p><%= @gossip.title%></p>
<p><%= @gossip.content%></p>


<p>
    <a href="<%= edit_gossip_path %>" class="btn btn-primary">Modifier votre Gossip</a>
</p>


<p>
    <a href="<%= root_path %>" class="btn btn-primary">Revenir aux articles</a>
</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "The Gossip Project", root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "L'équipe", team_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Contacts", contact_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Créer un compte", new_user_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
      <%= button_to "Se connecter", sessions_path,class: "btn btn-primary" %> 
      </li>
      <li class= 'dropdown'>
     <%= button_to "Se déconnecter", logout_path, method: "delete", class: "btn btn-danger" %>
     
      </li>
      <%# This is a comment in ERB <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#">Disabled</a>
      </li>%>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"></script>

    <%= stylesheet_link_tag "application"%>
    <%= javascript_importmap_tags %>
  </head>
  
  <body>
    <header>
      <%= render 'layouts/navbar' %>
    </header>
    <main>
      <%= yield %>
    </main>
    
  </body>
</html>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/home.html.erb
<div class="jumbotron">
        <div class="container">
        <br>
        <br>
<% if session[:user_id].present? %>
  <h2>Bienvenue <%= User.find_by(id: session[:user_id]).first_name %> !</h2>
<% end %>
<br>
<br>
<p class="text-center"><a href="<%= new_gossip_path %>" class="btn btn-primary">Créer un article</a></p>
<br>
<br>

<h2> Voici les gossips:</h2>


<table class="table">
  <% @gossip.each do |gossip| %>
    <tr>
      <td class="text-left"><%= link_to gossip.user.first_name, "/user/#{gossip.user.id}" %></td>
      <td class="text-center"><%= link_to gossip.title, "/gossip/#{gossip.id}" %></td>
    </tr>
  <% end %>
</table>


          
        </div>
      </div>

app/views/static_pages/team.html.erb
<h1>StaticPages#team</h1>
<p>Find me in app/views/static_pages/team.html.erb</p>

app/views/user/index.html.erb
<h1>Voici les Users:</h1>

<% @user.each do |user| %>
<p><%= user.first_name %></p>
<p><%= user.last_name %></p>
<% end %>

app/views/user/new.html.erb
<div class="container">
  <div class="row">

    <div class="col text-center">
      <h2>Créér un utilisateur</h2>
    </div>

    <div class="col-12">
        <div class="form-group">
          <%= form_tag url_for(action: 'create'), method: "post" do %>  
            <%= label_tag 'first_name' %>
            <%= text_area_tag 'first_name', @user.first_name, class: 'form-control' %>
            <br />
            <%= label_tag 'last_name' %>
            <%= text_area_tag 'last_name', @user.last_name, class: 'form-control' %>
            <br />
            <%= label_tag 'Email' %>
            <%= text_field_tag 'email', @user.email, class: 'form-control' %>
            <br />
            <%= label_tag 'Mot de passe' %>
            <%= text_area_tag 'password', @user.password, class: 'form-control' %>
            <br />                             
            <%= label_tag 'city' %>
            <%= text_area_tag 'city_name', @user.city_id, class: 'form-control' %>
            <br />
            <%= label_tag 'Description' %>
            <%= text_area_tag 'description', @user.description, class: 'form-control' %>
            <br />
            <%= label_tag 'Age' %>
            <%= text_area_tag 'age', @user.age, class: 'form-control' %>
            <br />
            <%= submit_tag "Inscription !", class: 'btn btn-success' %>
          <% end %>
        </div>

        <!-- affiche les erreurs qui empêchent la création du nouveau potin -->
        <% if @user.errors.any? %>
          <div class="alert alert-warning mt-2" role="alert">
            <p>Nous navons pas réussi à créer d'utilisateur pour la (ou les) raison(s) suivante(s) :</p>
              <ul>
                <% @user.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
              <p>Merci de réessayer</p>
        <% end %>
        </div>

    </div>
  </div>
</div>

app/views/user/show.html.erb
<h2> Voici le user n<%= @user.id %> </h2>
<p><%= @user.first_name%> </p>
<p><%= @user.last_name%></p>
<p><%= @user.age%></p>
<p><%= @user.description%></p>
<p><%= @user.city.name%></p>


<p>
    <a href="<%= root_path %>" class="btn btn-primary">Revenir aux articles</a>
</p>